import type { Metadata } from "next";
import "./globals.css";
import PortfolioHeader from "./Components/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="bg-pink-900 text-white">
        <div className="min-h-screen flex flex-col">
          <main className="flex-1  container m-20 bg-gray-900 rounded-3xl mx-auto ">
          <PortfolioHeader />
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
